---
- name: "install system packages"
  apt: name="{{ item }}" update_cache=yes state=present
  with_items:
    - gcc
    - g++
    - curl
    - wget
    - unzip
    - git
    - python-dev
    - python-apt
    - make
    - automake
    - autoconf
    - libreadline-dev
    - libncurses-dev
    - libssl-dev
    - libyaml-dev
    - libxslt-dev
    - libffi-dev
    - libtool
    - unixodbc-dev
  when: ansible_os_family == 'Debian'

- name: "install system packages"
  yum: name="{{ item }}" state=present
  with_items:
    - epel-release
    - gcc
    - gcc-c++
    - curl
    - wget
    - unzip
    - git
    - python-devel
    - make
    - automake
    - autoconf
    - readline-devel
    - ncurses-devel
    - openssl-devel
    - libyaml-devel
    - libxslt-devel
    - libffi-devel
    - libtool
    - unixODBC-devel
    # SEManage Tool
    - policycoreutils-python
  when: ansible_os_family == 'RedHat'

- name: should have credentials dir
  file: path=~/credentials state=directory
